### ISSUE TITLE
Spec plugin failure if setUp() fails during nose.suite.run()

### ISSUE THREAD

**Issue by dkjer** [bitprophet/spec#31]
Full traceback:

Traceback (most recent call last):
  File "agent_api/manage.py", line 12, in <module>
    execute_manager(settings)
  File "/ngi-persist/don/people-api-release/virtualenv/src/django/django/core/management/**init**.py", line 438, in execute_manager
    utility.execute()
  File "/ngi-persist/don/people-api-release/virtualenv/src/django/django/core/management/**init**.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/ngi-persist/don/people-api-release/virtualenv/src/django/django/core/management/base.py", line 191, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/ngi-persist/don/people-api-release/virtualenv/src/django/django/core/management/base.py", line 218, in execute
    output = self.handle(_args, *_options)
  File "/ngi-persist/don/people-api-release/virtualenv/src/django/django/core/management/commands/test.py", line 37, in handle
    failures = test_runner.run_tests(test_labels)
  File "/ngi-persist/don/people-api-release/virtualenv/lib/python2.6/site-packages/django_nose/runner.py", line 155, in run_tests
    result = self.run_suite(nose_argv)
  File "/ngi-persist/don/people-api-release/virtualenv/lib/python2.6/site-packages/django_nose/runner.py", line 117, in run_suite
    addplugins=plugins_to_add)
  File "/ngi-persist/don/people-api-release/virtualenv/lib/python2.6/site-packages/nose/core.py", line 118, in **init**
    *_extra_args)
  File "/usr/lib/python2.6/unittest.py", line 817, in **init**
    self.runTests()
  File "/ngi-persist/don/people-api-release/virtualenv/lib/python2.6/site-packages/nose/core.py", line 197, in runTests
    result = self.testRunner.run(self.test)
  File "/ngi-persist/don/people-api-release/virtualenv/lib/python2.6/site-packages/nose/core.py", line 61, in run
    test(result)
  File "/ngi-persist/don/people-api-release/virtualenv/lib/python2.6/site-packages/nose/suite.py", line 176, in **call**
    return self.run(_arg, *_kw)
  File "/ngi-persist/don/people-api-release/virtualenv/lib/python2.6/site-packages/nose/suite.py", line 223, in run
    test(orig)
  File "/ngi-persist/don/people-api-release/virtualenv/lib/python2.6/site-packages/nose/suite.py", line 176, in **call**
    return self.run(_arg, *_kw)
  File "/ngi-persist/don/people-api-release/virtualenv/lib/python2.6/site-packages/nose/suite.py", line 213, in run
    result.addError(self, self._exc_info())
  File "/ngi-persist/don/people-api-release/virtualenv/lib/python2.6/site-packages/nose/proxy.py", line 131, in addError
    plugins.addError(self.test, err)
  File "/ngi-persist/don/people-api-release/virtualenv/lib/python2.6/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(_arg, *_kw)
  File "/ngi-persist/don/people-api-release/virtualenv/lib/python2.6/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(_arg, **kw)
  File "/ngi-persist/don/people-api-release/virtualenv/lib/python2.6/site-packages/spec/plugin.py", line 393, in addError
    blurt('error', '')
  File "/ngi-persist/don/people-api-release/virtualenv/lib/python2.6/site-packages/spec/plugin.py", line 383, in blurt
    self._print_spec(color, test, label)
  File "/ngi-persist/don/people-api-release/virtualenv/lib/python2.6/site-packages/spec/plugin.py", line 511, in _print_spec
    if isinstance(test.test, doctest.DocTestCase) and not self.spec_doctests:
AttributeError: 'ContextSuite' object has no attribute 'test'

Suggested patch:
https://github.com/dkjer/spec/commit/2860388043accb3430a66a51ab64ef94f0061a57

**Comment by bendikro** [comment]
@bitprophet Any plans on fixing this?
