### ISSUE TITLE
1.4.1: pytest based test suite is failing

### ISSUE THREAD

**Issue by kloczek** [bitprophet/spec#47]
I'm not sure about testing methodoloby which should be used in case of this module.
Nevertheless I've been trying to use pytast nad it failed
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-spec-1.4.1-7.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-spec-1.4.1-7.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/python3 -Bm pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.9, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/tkloczko/rpmbuild/BUILD/spec-1.4.1
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, asyncio-0.14.0, expect-1.1.0, cov-2.11.1, mock-3.5.1, httpbin-1.0.0, xdist-2.2.1, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, pyfakefs-4.4.0, freezegun-0.4.2, flaky-3.7.0, cases-3.4.6, hypothesis-6.10.0
collected 0 items / 1 error

================================================================================== ERRORS ==================================================================================
___________________________________________________________________ ERROR collecting tests/spec_test.py ____________________________________________________________________
tests/spec_test.py:133: in <module>
    class TestPluginSpecWithDoctests(_SpecPluginTestCase):
tests/spec_test.py:136: in TestPluginSpecWithDoctests
    plugins = [Spec(), nose.plugins.doctests.Doctest()]
E   AttributeError: module 'nose.plugins' has no attribute 'doctests'
========================================================================= short test summary info ==========================================================================
ERROR tests/spec_test.py - AttributeError: module 'nose.plugins' has no attribute 'doctests'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 1 error in 0.24s =============================================================================
```

**Comment by kloczek** [comment]
`setuptools` based testing are failing as well.
```console
+ /usr/bin/python3 setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing spec.egg-info/PKG-INFO
writing dependency_links to spec.egg-info/dependency_links.txt
writing entry points to spec.egg-info/entry_points.txt
writing requirements to spec.egg-info/requires.txt
writing top-level names to spec.egg-info/top_level.txt
reading manifest file 'spec.egg-info/SOURCES.txt'
writing manifest file 'spec.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    setup(
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/site-packages/setuptools/command/test.py", line 238, in run
    self.run_tests()
  File "/usr/lib/python3.8/site-packages/setuptools/command/test.py", line 256, in run_tests
    test = unittest.main(
  File "/usr/lib64/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.8/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib64/python3.8/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib64/python3.8/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib64/python3.8/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib64/python3.8/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/usr/lib64/python3.8/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3.8/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.8/unittest/loader.py", line 205, in loadTestsFromName
    test = obj()
TypeError: trap() missing 1 required positional argument: 'func'
```

**Comment by kloczek** [comment]
`nose` module is outdated and should not be used with python 3.x.

**Comment by kloczek** [comment]
Closing. Looks like module is no longer used by anything what I have.
